# Generated by Django 4.2.6 on 2023-10-18 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plane', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
